### ISSUE TITLE
[View > Files] Home is not shown for read-only Tales

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#29] opened 2020-04-14 13:48 UTC
**Steps to Reproduce**
**Steps to Reproduce**
1. Deploy and register LIGO Tale
1. *Tale Dashboard* > *Public Tales*: click "View" on "LIGO Tutorial"
1. Click on the *Files* tab

**Expected Results**
`Home` should be one of the options

**Actual Results**
`Home` is missing

**NOTES**
While it's not necessarily a bad thing, I'm reporting it as a difference wrt old dashboard.

**Comment by bodom0015** [comment] 2020-05-04 20:31
This was apparently by design: https://whole-tale.github.io/wholetale-css-mockup/src/run-files-pre-run.html

The newest iteration of mockups do not appear to show "Home" for read-only Tales. The test plan may need to be updated to reflect this new behavior.

**Comment by bodom0015** [comment] 2020-09-21 19:24
Discussed briefly on the dev call 9/21/2020. We all agreed that it seemed confusing to show "Home" under contexts where it's contents could not be used.

Closing this unless the feature is explicitly requested at a later date.

**Closed by bodom0015** 2020-09-21 19:24 UTC
Labels: bug, question
